name:                poly
version:             0.1.0.0
homepage:            https://github.com/artemisYo/poly
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - monomer
  - process
  - text
  - containers
  - Hustle

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  poly:
    source-dirs:      src
    main:             Main.hs
